config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'

  resources :issues
  resources :users
    root 'application#hello'
end

HelloApp::Application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/google_user.rb
class GoogleUser < ActiveRecord::Base
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |google_users|
          google_users.provider = auth.provider
          google_users.uid = auth.uid
          google_users.name = auth.info.name
          google_users.oauth_token = auth.credentials.token
          google_users.oauth_expires_at = Time.at(auth.credentials.expires_at)
          google_users.save!
    end
  end
end

app/models/issue.rb
class Issue < ApplicationRecord
    belongs_to :user
     #validates :Title, :Type, :Priority, :Status, presence: true
    
    def self.status
        ["New", "Open", "On hold", "Resolved", "Duplicate", "Invalid", "Won't fix", "Closed"]
    end
    def self.tipus
        ["Bug", "Enhancement", "Proposal", "Task"]
    end
    def self.priority
        ["Trivial", "Minor", "Major", "Critical", "Blocker"]
end
end
   # enum priority: [:trivial, :minor, :major, :critical, :blocker]
    #enum tipus: [:bug, :enhancement, :proposal, :task]
    #enum status: [:open, :onhold, :resolved, :duplicate, :notvalid, :wontfix, :closed]
#end*/

app/models/user.rb
class User < ApplicationRecord
    has_many :issues
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= GoogleUser.find(session[:user_id]) if session[:user_id]
  end
  
  def hello
    redirect_to "/issues"
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.order(sort_column + ' ' + sort_direction)
  end
  
  def sort_column
    Issue.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)
    @issue.created_at = Time.now
    @issue.updated_at = Time.now
    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    @issue = Issue.find(params[:id])
    @issue.updated_at = Time.now
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def Votes 
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:content, :user_id, :title, :tipus, :priority, :status, :votes, :assignee, :created_at, :updated_at)
    end
    
    private
    # A list of the param names that can be used for filtering the Product list
    def filtering_params(params)
      params.slice(:content, :user_id, :title, :tipus, :priority, :status, :votes, :assignee, :created_at, :updated_at)
    end
    
    
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = GoogleUser.from_omniauth(env["omniauth.auth"])
    session[:user_id] = google_users.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/show.html.erb
<h1>Login</h1>
<p>Please login using google</p>

app/views/issues/_form.html.erb
<%= form_with(model: issue, local: true) do |form| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, id: :issue_title %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :issue_user_id %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :issue_content %>
  </div>

  <div class="field">
    <%= form.label :tipus %>
    <%= form.select :tipus, options_for_select(Issue.tipus, issue[:tipus]), id: :issue_tipus %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, options_for_select(Issue.priority, issue[:Priority]), id: :issue_priority %>
  </div>

  <div class="field">
    <%= form.label :status %>
    
    <%=  form.select :status, options_for_select(Issue.status), id: :issue_status %>
  </div>

  <div class="field">
    <%= form.label :votes %>
    <%= form.number_field :votes, id: :issue_votes %>
  </div>

  <div class="field">
    <%= form.label :assignee %>
    <%= form.text_field :assignee, id: :issue_assignee %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Issues</h1>

<table>
  <thead>
    <tr>
      <th><%= sortable "title" %></th>
      <th><%= sortable "user_id" %></th>
      <th><%= sortable "content" %></th>
      <th><%= sortable "tipus" %></th>
      <th><%= sortable "priority" %></th>
      <th><%= sortable "status" %></th>
      <th><%= sortable "votes" %></th>
      <th><%= sortable "assignee" %></th>
      <th><%= sortable "created_at" %></th>
      <th><%= sortable "updated_at" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= link_to issue.title, issue %></td>
        <td><%= issue.user_id %></td>
        <td><%= issue.content %></td>
        <td><%= issue.tipus %></td>
        <td><%= issue.priority %></td>
        <td><%= issue.status %></td>
        <td><%= issue.votes %></td>
        <td><%= issue.assignee %></td>
        <td><%= issue.created_at.strftime("%m/%d/%y, %H:%M") %></td>
        <td><%= issue.updated_at.strftime("%m/%d/%y, %H:%M") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @issue.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @issue.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @issue.content %>
</p>

<p>
  <strong>Type:</strong>
  <%= @issue.tipus %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @issue.priority %>
</p>

<p>
  <strong>Status:</strong>
  <%= @issue.status %>
</p>

<p>
  <strong>Votes:</strong>
  <%= @issue.votes %>
  
  <%= link_to 'Add Vote' %>
  
</p>

<p>
  <strong>Assignee:</strong>
  <%= @issue.assignee %>
</p>

<p>
  <strong>Created:</strong>
  <%= @issue.created_at.strftime("%m/%d/%y, %H:%M") %>
</p>

<p>
  <strong>Updated:</strong>
  <%= @issue.updated_at.strftime("%m/%d/%y, %H:%M") %>
</p>


<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Destroy', @issue, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', issues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Google Auth Example App</title>
    <%= stylesheet_link_tag    "application.css", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div>
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
      <% end %>
    </div>
    <div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>